import React from 'react';
import { View, Text } from 'react-native';
import { useRouter } from 'expo-router';
import { ScreenWrapper, AppHeader } from '../../src/components';
import { spacing, typography } from '../../src/theme';
import { useTheme } from '../../src/context/ThemeContext';
import { useLanguage } from '../../src/context/LanguageContext';

function Section({ title, body }: { title: string; body: string }) {
  const { colors } = useTheme();
  return (
    <View style={{ marginBottom: spacing.xxl }}>
      <Text style={{ ...typography.h3, color: colors.text.primary, marginBottom: spacing.md }}>{title}</Text>
      <Text style={{ ...typography.body, color: colors.text.secondary, lineHeight: 24 }}>{body}</Text>
    </View>
  );
}

export default function TermsScreen() {
  const router = useRouter();
  const { colors } = useTheme();
  const { t } = useLanguage();

  return (
    <ScreenWrapper scroll>
      <AppHeader showBack onBack={() => router.back()} title={t('titleTerms')} />

      <Text style={{ ...typography.caption, color: colors.text.muted, marginBottom: spacing.xxl }}>
        Last updated: January 1, 2026
      </Text>

      <Section
        title="1. Acceptance of Terms"
        body="By downloading, installing, or using EntrepreneurAI, you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the app. These terms apply to all users of the app."
      />

      <Section
        title="2. Use of Service"
        body="EntrepreneurAI provides educational content, AI coaching, and community features for aspiring entrepreneurs. You agree to use the service lawfully and not to: violate any laws, infringe on others' intellectual property, engage in harassment or hate speech, or attempt to reverse engineer the app."
      />

      <Section
        title="3. Subscriptions"
        body="EntrepreneurAI offers free and Pro subscription tiers. Pro subscriptions are billed monthly, annually, or as a one-time lifetime purchase. Subscriptions auto-renew unless cancelled at least 24 hours before the renewal date. Prices may change with 30 days notice."
      />

      <Section
        title="4. Refund Policy"
        body="Refunds are governed by Apple App Store and Google Play Store policies. We do not offer direct refunds outside of platform policies. If you believe you were charged in error, contact support@entrepreneurai.com within 7 days."
      />

      <Section
        title="5. Community Rules"
        body="Our community features require respectful conduct. Prohibited content includes: spam, misinformation, adult content, personal attacks, and content that violates others' privacy. Violations may result in account suspension or termination."
      />

      <Section
        title="6. Intellectual Property"
        body="All content in EntrepreneurAI — including courses, AI responses, graphics, and code — is owned by EntrepreneurAI or its licensors. You may not copy, distribute, or create derivative works without express written permission."
      />

      <Section
        title="7. AI Disclaimer"
        body="AI Coach responses are generated by artificial intelligence and are for educational purposes only. They do not constitute professional financial, legal, or business advice. Always consult qualified professionals for important business decisions."
      />

      <Section
        title="8. Limitation of Liability"
        body="EntrepreneurAI is provided 'as is' without warranties. We are not liable for any indirect, incidental, or consequential damages arising from use of the app. Our total liability to you shall not exceed the amount you paid in the last 12 months."
      />

      <Section
        title="9. Termination"
        body="We reserve the right to suspend or terminate accounts that violate these terms. You may terminate your account at any time through Settings > Privacy & Security > Delete Account."
      />

      <Section
        title="10. Contact"
        body="Questions about these terms? Contact us at:\n\nEmail: legal@entrepreneurai.com\n© 2026 EntrepreneurAI. All rights reserved."
      />
    </ScreenWrapper>
  );
}
